// Entry point for hosts that run a single, persistent Node.js process and
// need one JS file to execute (e.g. Hostinger's Node.js Web App hosting).
// Point that host's "Application startup file" setting at this file.
//
// The actual server is generated by `next build` (see next.config.ts's
// `output: "standalone"`) into .next/standalone/server.js, self-contained
// with its own trimmed node_modules. package.json's "postbuild" script
// copies the static assets it also needs (public/, .next/static) into that
// same folder right after the build finishes.
// eslint-disable-next-line @typescript-eslint/no-require-imports
require("./.next/standalone/server.js");
